<?php
/**
 * Fichier de la classe Template.
 *
 * PHP version 5
 *
 * @category Framework
 * @package  SWAF\Core
 * @author   Van den Branden Maxime <max.van.den.branden@gmail.com>
 * @license  PHP License 3.01
 * @version  GIT: git://github.com/Maxs1789/SWAF.git
 * @link     https://github.com/Maxs1789/SWAF
 */
namespace SWAF\Core;

/**
 * Classe de génération de template.
 *
 * @category Framework
 * @package  SWAF\Core
 * @author   Van den Branden Maxime <max.van.den.branden@gmail.com>
 * @license  http://www.php.net/license/3_01.txt PHP License 3.01
 * @version  Release: 0.1
 * @link     https://github.com/Maxs1789/SWAF
 */
class Template
{
    /**
     * Expression régulière pour une variable.
     *
     * @var string
     */
    const REG_VAR = '\$((\{(\.?[[:alnum:]_]+)+\})+)';
    /**
     * Expression régulière pour un bloc.
     *
     * @var string
     */
    const REG_BLOCK = '<!-- *([[:alpha:]]+) *(((?!-->).)*) *-->';

    /**
     * Tableau des variables pour la génération.
     *
     * @var array
     */
    private $_vars = array(
        'SWAF'     => array(
            'version' => SWAF_VERSION
        ),
        'TEMPLATE' => array(
            'version' => '0.1'
        )
    );
    /**
     * Tableau des fonctions de remplacement des blocs.
     *
     * @var array
     */
    private $_replaceBlockFunctions = array(
        'IF'       => '_replaceIf',
        'ELSE'     => '_replaceElse',
        'END'      => '_replaceEnd',
        'BLOCK'    => '_replaceBlock',
        'FIRST'    => '_replaceFirst',
        'LAST'     => '_replaceLast',
        'EVEN'     => '_replaceEven',
        'ODD'      => '_replaceOdd',
        'EMPTY'    => '_replaceEmpty',
        'ENDBLOCK' => '_replaceEndBlock',
        'INCLUDE'  => '_replaceInclude',
        ''         => ''
    );

    /**
     * Assigne une variable pour la génération.
     *
     * @param string $varName Nom de la variable à assigner.
     * @param mixed  $var     Valeur à assigner à la variable.
     *
     * @return null
     */
    public function setVar ($varName, $var)
    {
        $this->_vars[$varName] = $var;
    }

    /**
     * Assigne des variables pour la génération.
     *
     * @param array $vars Tableau des variables à assigner.
     *
     * @return null
     */
    public function setVars ($vars)
    {
        foreach ($vars as $varName => $var) {
            $this->_vars[$varName] = $var;
        }
    }

    /**
     * Supprime une variable.
     *
     * @param string $varName Nom de la variable.
     *
     * @return null
     */
    public function unsetVar ($varName)
    {
        unset($this->_vars[$varName]);
    }

    /**
     * Vérifie qu'un variable est assignée.
     *
     * @param string $varName Nom de la variable à effacer.
     *
     * @return bool true si la variable est assignée, false sinon.
     */
    public function issetVar ($varName)
    {
        return isset($this->_vars[$varName]);
    }

    /**
     * Retourne une variable.
     *
     * @param string $varName Nom de la variable à effacer.
     *
     * @return mixed Valeur de la variable ou null si celle-ci n'existe pas.
     */
    public function getVar ($varName)
    {
        if (!isset($this->_vars[$varName])) {
            return null;
        }
        return $this->_vars[$varName];
    }

    /**
     * Affiche et génère si nécessaire un fichier template.
     *
     * @param string $fileName Nom du fichier à afficher.
     *
     * @return null
     */
    function display ($fileName)
    {
        if (!FileManager::checkForCache($fileName)) {
            $this->_generate(realpath($fileName));
        }

        include FileManager::cachepath($fileName).'.php';
    }

    /**
     * Génère le fichier template.
     *
     * @param string $fileName Nom du fichier à afficher.
     *
     * @return null
     * @throw FileException Si le fichier ne peut être lu.
     */
    private function _generate ($fileName)
    {
        FileException::checkReadable($fileName);

        $handle = fopen($fileName, 'rb');
        $html = fread($handle, filesize($fileName));
        fclose($handle);

        $html = $this->_replaceBlocks($html);
        $html = $this->_replaceVars($html);

        $html = ' * '.date('r')."\n */ ?>\n$html";
        $html = "<?php\n/* generated by SWAF\Core\Template\n$html";

        $html = preg_replace_callback(
            '#\?>(( |\n|\t|\r|)*)<\?php#',
            function ($matches) {
                return $matches[0];
            },
            $html
        );

        $cache = FileManager::cachepath($fileName).'.php';
        $handle = fopen($cache, 'wb');
        fwrite($handle, $html);
        fclose($handle);
    }

    /**
     * Fonction de remplacement des blocs template.
     *
     * @param string $tpl Template à modifier.
     *
     * @return string Le template généré.
     */
    private function _replaceBlocks ($tpl)
    {
        return preg_replace_callback(
            '#'.self::REG_BLOCK.'#',
            function ($matches) {
                $blockType = isset($matches[1]) ? strtoupper($matches[1]) : '';
                $exp = isset($matches[2]) ? $matches[2] : '';
                $func = $this->_replaceBlockFunctions[$blockType];
                if ($func == '') {
                    return '';
                }
                return $this->$func($exp);
            },
            $tpl
        );
    }

    /**
     * Fonction de remplacement des variables template.
     *
     * @param string $tpl  Template à modifier.
     * @param bool   $echo Permet d'afficher directement les variables.
     *
     * @return string Le template généré.
     */
    private function _replaceVars ($tpl, $echo = true)
    {
        return preg_replace_callback(
            '#'.self::REG_VAR.'#',
            function ($matches) use ($echo) {
                $var = $this->_var($matches[1]);
                if (!$echo) {
                    return "(isset($var) ? $var : false)";
                }
                return "<?php echo isset($var) ? $var : ''; ?>";
            },
            $tpl
        );
    }
    /**
     * Fonction de remplacement d'une variable template.
     *
     * @param string $var Variable sous forme de template.
     *
     * @return string Variable dans le contexte.
     */
    private function _var ($var)
    {
        $subVars = explode('{', $this->_clearVar($var));
        $base    = $subVars[0];
        $realVar = $this->_baseVar($base);

        for ($i = 1; $i < count($subVars); $i++) {
            $realVar .= '['.$this->_varCounter($base).']';
            $realVar .= $this->_baseVar($subVars[$i]);
            $base    .= '.'.$subVars[$i];
        }
        return '$this->_vars'.$realVar;
    }

    /**
     * Fonction de remplacement d'une variable template simple.
     *
     * @param string $var Variable sous forme de template simple.
     *
     * @return string Base du nom de la variable dans le contexte.
     */
    private function _baseVar ($var)
    {
        $baseVar = str_replace('.', "']['", $var);
        return "['$baseVar']";
    }

    /**
     * Nettoie une variable template en vue d'être traité par les autres
     * fonctions de remplacement.
     *
     * @param string $var Variable sous forme de template.
     *
     * @return string variable nettoyé.
     */
    private function _clearVar ($var)
    {
        return preg_replace('#(^\$?\{)|\}| #', '', $var);
    }

    /**
     * Retourne le compteur correspondant à une variable template.
     *
     * @param string $var Variable sous forme de template.
     *
     * @return string Compteur.
     */
    private function _varCounter ($var)
    {
        $c = preg_replace('#\{|\.#', '_', $this->_clearVar($var));
        return "\$_$c";
    }

    /**
     * Fonction de remplacement d'un bloc `IF`.
     *
     * @param string $exp Expression du bloc.
     *
     * @return string Code de remplacement.
     */
    private function _replaceIf ($exp)
    {
        $condition = $this->_replaceVars($exp, false);
        return "<?php if ($condition) { ?>";
    }

    /**
     * Fonction de remplacement d'un bloc `ELSE`.
     *
     * @param string $exp Expression du bloc.
     *
     * @return string Code de remplacement.
     */
    private function _replaceElse ($exp)
    {
        return '<?php } else { ?>';
    }

    /**
     * Fonction de remplacement d'un bloc `END`.
     *
     * @param string $exp Expression du bloc.
     *
     * @return string Code de remplacement.
     */
    private function _replaceEnd ($exp)
    {
        return '<?php } ?>';
    }

    /**
     * Fonction de remplacement d'un bloc `BLOCK`.
     *
     * @param string $exp Expression du bloc.
     *
     * @return string Code de remplacement.
     */
    private function _replaceBlock ($exp)
    {
        $var = $this->_var($exp);
        $i   = $this->_varCounter($exp);
        return "<?php if (isset($var)) {
                for ($i = 0; $i < count($var); $i++) { ?>"
        ;
    }

    /**
     * Fonction de remplacement d'un bloc `FIRST`.
     *
     * @param string $exp Expression du bloc.
     *
     * @return string Code de remplacement.
     */
    private function _replaceFirst ($exp)
    {
        $i = $this->_varCounter($exp);
        return "<?php if ($i == 0) { ?>";
    }

    /**
     * Fonction de remplacement d'un bloc `LAST`.
     *
     * @param string $exp Expression du bloc.
     *
     * @return string Code de remplacement.
     */
    private function _replaceLast ($exp)
    {
        $var = $this->_var($exp);
        $i   = $this->_varCounter($exp);
        return "<?php if ($i == count($var) - 1) { ?>";
    }

    /**
     * Fonction de remplacement d'un bloc `EVEN`.
     *
     * @param string $exp Expression du bloc.
     *
     * @return string Code de remplacement.
     */
    private function _replaceEven ($exp)
    {
        $i = $this->_varCounter($exp);
        return "<?php if ($i % 2 == 1) { ?>";
    }

    /**
     * Fonction de remplacement d'un bloc `ODD`.
     *
     * @param string $exp Expression du bloc.
     *
     * @return string Code de remplacement.
     */
    private function _replaceOdd ($exp)
    {
        $i = $this->_varCounter($exp);
        return "<?php if ($i % 2 == 0) { ?>";
    }

    /**
     * Fonction de remplacement d'un bloc `EMPTY`.
     *
     * @param string $exp Expression du bloc.
     *
     * @return string Code de remplacement.
     */
    private function _replaceEmpty ($exp)
    {
        $var = $this->_var($exp);
        return "<?php }} if (!isset($var) || count($var) == 0) {{ ?>";
    }

    /**
     * Fonction de remplacement d'un bloc `ENDBLOCK`.
     *
     * @param string $exp Expression du bloc.
     *
     * @return string Code de remplacement.
     */
    private function _replaceEndBlock ($exp)
    {
        return '<?php }} ?>';
    }

    /**
     * Fonction de remplacement d'un bloc `INCLUDE`.
     *
     * @param string $exp Expression du bloc.
     *
     * @return string Code de remplacement.
     */
    private function _replaceInclude ($exp)
    {
        return '<?php \SWAF\Core\ViewManager::display(\''.$exp.'\') ?>';
    }
}
?>
